// Source: https://unicode-org.github.io/cldr-staging/charts/latest/supplemental/territory_containment_un_m_49.html
import { InjectionToken } from '@angular/core';

export interface Region {
  region: string,
  code: string
}

export const REGIONS = new InjectionToken<Region[]>('root', {
  factory() {
    return regions;
  }
})

const regions: Region[] = [
  { region: 'Afghanistan', code: 'AF' },
  { region: 'Albania', code: 'AL' },
  { region: 'Algeria', code: 'DZ' },
  { region: 'Andorra', code: 'AD' },
  { region: 'Angola', code: 'AO' },
  { region: 'Antigua & Barbuda', code: 'AG' },
  { region: 'Argentina', code: 'AR' },
  { region: 'Armenia', code: 'AM' },
  { region: 'Australia', code: 'AU' },
  { region: 'Austria', code: 'AT' },
  { region: 'Azerbaijan', code: 'AZ' },
  { region: 'Bahamas', code: 'BS' },
  { region: 'Bahrain', code: 'BH' },
  { region: 'Bangladesh', code: 'BD' },
  { region: 'Barbados', code: 'BB' },
  { region: 'Belarus', code: 'BY' },
  { region: 'Belgium', code: 'BE' },
  { region: 'Belize', code: 'BZ' },
  { region: 'Benin', code: 'BJ' },
  { region: 'Bhutan', code: 'BT' },
  { region: 'Bolivia', code: 'BO' },
  { region: 'Bosnia & Herzegovina', code: 'BA' },
  { region: 'Botswana', code: 'BW' },
  { region: 'Brazil', code: 'BR' },
  { region: 'Brunei', code: 'BN' },
  { region: 'Bulgaria', code: 'BG' },
  { region: 'Burkina Faso', code: 'BF' },
  { region: 'Burundi', code: 'BI' },
  { region: 'Cambodia', code: 'KH' },
  { region: 'Cameroon', code: 'CM' },
  { region: 'Canada', code: 'CA' },
  { region: 'Cape Verde', code: 'CV' },
  { region: 'Central African Republic', code: 'CF' },
  { region: 'Chad', code: 'TD' },
  { region: 'Chile', code: 'CL' },
  { region: 'China', code: 'CN' },
  { region: 'Colombia', code: 'CO' },
  { region: 'Comoros', code: 'KM' },
  { region: 'Congo - Brazzaville', code: 'CG' },
  { region: 'Congo - Kinshasa', code: 'CD' },
  { region: 'Costa Rica', code: 'CR' },
  { region: 'Croatia', code: 'HR' },
  { region: 'Cuba', code: 'CU' },
  { region: 'Cyprus', code: 'CY' },
  { region: 'Czechia', code: 'CZ' },
  { region: 'Côte d’Ivoire', code: 'CI' },
  { region: 'Denmark', code: 'DK' },
  { region: 'Djibouti', code: 'DJ' },
  { region: 'Dominica', code: 'DM' },
  { region: 'Dominican Republic', code: 'DO' },
  { region: 'Ecuador', code: 'EC' },
  { region: 'Egypt', code: 'EG' },
  { region: 'El Salvador', code: 'SV' },
  { region: 'Equatorial Guinea', code: 'GQ' },
  { region: 'Eritrea', code: 'ER' },
  { region: 'Estonia', code: 'EE' },
  { region: 'Eswatini', code: 'SZ' },
  { region: 'Ethiopia', code: 'ET' },
  { region: 'Eurozone', code: 'EZ' },
  { region: 'Fiji', code: 'FJ' },
  { region: 'Finland', code: 'FI' },
  { region: 'France', code: 'FR' },
  { region: 'Gabon', code: 'GA' },
  { region: 'Gambia', code: 'GM' },
  { region: 'Georgia', code: 'GE' },
  { region: 'Germany', code: 'DE' },
  { region: 'Ghana', code: 'GH' },
  { region: 'Greece', code: 'GR' },
  { region: 'Grenada', code: 'GD' },
  { region: 'Guatemala', code: 'GT' },
  { region: 'Guinea', code: 'GN' },
  { region: 'Guinea-Bissau', code: 'GW' },
  { region: 'Guyana', code: 'GY' },
  { region: 'Haiti', code: 'HT' },
  { region: 'Honduras', code: 'HN' },
  { region: 'Hungary', code: 'HU' },
  { region: 'Iceland', code: 'IS' },
  { region: 'India', code: 'IN' },
  { region: 'Indonesia', code: 'ID' },
  { region: 'Iran', code: 'IR' },
  { region: 'Iraq', code: 'IQ' },
  { region: 'Ireland', code: 'IE' },
  { region: 'Israel', code: 'IL' },
  { region: 'Italy', code: 'IT' },
  { region: 'Jamaica', code: 'JM' },
  { region: 'Japan', code: 'JP' },
  { region: 'Jordan', code: 'JO' },
  { region: 'Kazakhstan', code: 'KZ' },
  { region: 'Kenya', code: 'KE' },
  { region: 'Kiribati', code: 'KI' },
  { region: 'Kuwait', code: 'KW' },
  { region: 'Kyrgyzstan', code: 'KG' },
  { region: 'Laos', code: 'LA' },
  { region: 'Latvia', code: 'LV' },
  { region: 'Lebanon', code: 'LB' },
  { region: 'Lesotho', code: 'LS' },
  { region: 'Liberia', code: 'LR' },
  { region: 'Libya', code: 'LY' },
  { region: 'Liechtenstein', code: 'LI' },
  { region: 'Lithuania', code: 'LT' },
  { region: 'Luxembourg', code: 'LU' },
  { region: 'Madagascar', code: 'MG' },
  { region: 'Malawi', code: 'MW' },
  { region: 'Malaysia', code: 'MY' },
  { region: 'Maldives', code: 'MV' },
  { region: 'Mali', code: 'ML' },
  { region: 'Malta', code: 'MT' },
  { region: 'Marshall Islands', code: 'MH' },
  { region: 'Mauritania', code: 'MR' },
  { region: 'Mauritius', code: 'MU' },
  { region: 'Mexico', code: 'MX' },
  { region: 'Micronesia', code: 'FM' },
  { region: 'Moldova', code: 'MD' },
  { region: 'Monaco', code: 'MC' },
  { region: 'Mongolia', code: 'MN' },
  { region: 'Montenegro', code: 'ME' },
  { region: 'Morocco', code: 'MA' },
  { region: 'Mozambique', code: 'MZ' },
  { region: 'Myanmar (Burma)', code: 'MM' },
  { region: 'Namibia', code: 'NA' },
  { region: 'Nauru', code: 'NR' },
  { region: 'Nepal', code: 'NP' },
  { region: 'Netherlands', code: 'NL' },
  { region: 'New Zealand', code: 'NZ' },
  { region: 'Nicaragua', code: 'NI' },
  { region: 'Niger', code: 'NE' },
  { region: 'Nigeria', code: 'NG' },
  { region: 'North Korea', code: 'KP' },
  { region: 'North Macedonia', code: 'MK' },
  { region: 'Norway', code: 'NO' },
  { region: 'Oman', code: 'OM' },
  { region: 'Pakistan', code: 'PK' },
  { region: 'Palau', code: 'PW' },
  { region: 'Panama', code: 'PA' },
  { region: 'Papua New Guinea', code: 'PG' },
  { region: 'Paraguay', code: 'PY' },
  { region: 'Peru', code: 'PE' },
  { region: 'Philippines', code: 'PH' },
  { region: 'Poland', code: 'PL' },
  { region: 'Portugal', code: 'PT' },
  { region: 'Qatar', code: 'QA' },
  { region: 'Romania', code: 'RO' },
  { region: 'Russia', code: 'RU' },
  { region: 'Rwanda', code: 'RW' },
  { region: 'Samoa', code: 'WS' },
  { region: 'San Marino', code: 'SM' },
  { region: 'Saudi Arabia', code: 'SA' },
  { region: 'Senegal', code: 'SN' },
  { region: 'Serbia', code: 'RS' },
  { region: 'Seychelles', code: 'SC' },
  { region: 'Sierra Leone', code: 'SL' },
  { region: 'Singapore', code: 'SG' },
  { region: 'Slovakia', code: 'SK' },
  { region: 'Slovenia', code: 'SI' },
  { region: 'Solomon Islands', code: 'SB' },
  { region: 'Somalia', code: 'SO' },
  { region: 'South Africa', code: 'ZA' },
  { region: 'South Korea', code: 'KR' },
  { region: 'South Sudan', code: 'SS' },
  { region: 'Spain', code: 'ES' },
  { region: 'Sri Lanka', code: 'LK' },
  { region: 'St. Kitts & Nevis', code: 'KN' },
  { region: 'St. Lucia', code: 'LC' },
  { region: 'St. Vincent & Grenadines', code: 'VC' },
  { region: 'Sudan', code: 'SD' },
  { region: 'Suriname', code: 'SR' },
  { region: 'Sweden', code: 'SE' },
  { region: 'Switzerland', code: 'CH' },
  { region: 'Syria', code: 'SY' },
  { region: 'São Tomé & Príncipe', code: 'ST' },
  { region: 'Tajikistan', code: 'TJ' },
  { region: 'Tanzania', code: 'TZ' },
  { region: 'Thailand', code: 'TH' },
  { region: 'Timor-Leste', code: 'TL' },
  { region: 'Togo', code: 'TG' },
  { region: 'Tonga', code: 'TO' },
  { region: 'Trinidad & Tobago', code: 'TT' },
  { region: 'Tunisia', code: 'TN' },
  { region: 'Turkey', code: 'TR' },
  { region: 'Turkmenistan', code: 'TM' },
  { region: 'Tuvalu', code: 'TV' },
  { region: 'Uganda', code: 'UG' },
  { region: 'Ukraine', code: 'UA' },
  { region: 'United Arab Emirates', code: 'AE' },
  { region: 'United Kingdom', code: 'GB' },
  { region: 'United Nations', code: 'UN' },
  { region: 'United States', code: 'US' },
  { region: 'Uruguay', code: 'UY' },
  { region: 'Uzbekistan', code: 'UZ' },
  { region: 'Vanuatu', code: 'VU' },
  { region: 'Venezuela', code: 'VE' },
  { region: 'Vietnam', code: 'VN' },
  { region: 'Yemen', code: 'YE' },
  { region: 'Zambia', code: 'ZM' },
  { region: 'Zimbabwe', code: 'ZW' }
]
